### PR TITLE
Update Chinese Simplified translation (once again)

### PR DESCRIPTION
**Pull request by imgradeone**
Sorry for this :(

because the translation still need to edit *.xlf files, and my translations ( #134 ) didn't work

### CODE REVIEW

**Comment by imgradeone** [comment]
then I still need to edit the *.resx files

so I just drafted

**Comment by imgradeone** [comment]
now ready

**Review by Samuel12321 — APPROVED** [review]
Looks good thanks.
Will merge once 0.8 is closer to being finished.

**Comment by Samuel12321** [comment]
Hi @imgradeone , 0.8.0.0 has been released, introducing significant changes. Can you update your translations for this release?

Thanks so much for your help.
This will be immediately merged once the translations are updated.

**Comment by imgradeone** [comment]
> Hi @imgradeone , 0.8.0.0 has been released, introducing significant changes. Can you update your translations for this release?
> 
> Thanks so much for your help.
> This will be immediately merged once the translations are updated.

@ShankarBUS OK, I will do that asap.
then I need to sync with the upstream

**Comment by imgradeone** [comment]
wait a minute
there are some issue to solve

**Comment by ShankarBUS** [comment]
Why did you close this @imgradeone?

**Comment by imgradeone** [comment]
hmm, I just synced with upstream, then it has automatically closed :(

**Comment by ShankarBUS** [comment]
@imgradeone ok

**Comment by imgradeone** [comment]
now repoened

**Comment by ShankarBUS** [comment]
Great!

**Review by Samuel12321 — APPROVED** [review]
Looks great.
Thanks so much for your help. Sorry about the repeats.

**Pull request merged**
