### PR TITLE
.NET5

### PR DESCRIPTION
**Pull request by Samuel12321**
What i currently have for .NET5 
Only works as x86

#28

### CODE REVIEW

**Comment by ShankarBUS** [comment]
Don't release this version to the store immediately after merging this.

I would have to port a dependency to .NET 5

**Comment by ShankarBUS** [comment]
Thanks BTW!

I was working on another project in the mean time. It would've been hard for me to hold on to two projects 👍.

Thanks for staying together 😃

**Comment by Samuel12321** [comment]
wont merge it till its properly fixed

**Comment by ShankarBUS** [comment]
Could you merge it? Are there any issues?

**Comment by Samuel12321** [comment]
There is a problem with building for non x86. Other than that its fine.

**Comment by Cyberdroid1** [comment]
When can we expect the store version? Directly at 0.7 or will we get 0.6.5?

**Comment by Samuel12321** [comment]
Not sure, I'm communicating with @ShankarBUS about this, not sure there is any benefit as the end user wont notice the change (at least not until its fully implemented). Additionally it is currently X86 only.

**Comment by Cyberdroid1** [comment]
Then lets skip directly to 0.7 for the store.

**Comment by Samuel12321** [comment]
Agreed

**Comment by ShankarBUS** [comment]
v0.7 would take a little longer to release 😅.

**Comment by Samuel12321** [comment]
first priority for 0.7 needs to be conversion to .dll

**Comment by ShankarBUS** [comment]
Why? Converting ModernFlyouts to a *.dll is not the first step.

Without an executable, the application would work!

**Comment by Cyberdroid1** [comment]
> v0.7 would take a little longer to release 😅.

No problem with that. It will be less work and easier handling if you don't release 0.6.5 for the store.

**Pull request merged**
