### PR TITLE
Remove bad words from readme

### PR DESCRIPTION
**Pull request by Tarik02**
image

image

### CODE REVIEW

**Review by Samuel12321 — APPROVED** [review]
Thankyou so much for picking up on this.
@yukiokun057, we are terribly sorry about this 
I will look into how this got onto our readme.

**Comment by yukiokun057** [comment]
Hehe. It's OK. You can keep the old variant😅

**Comment by ShankarBUS** [comment]
Oh! It was me sorry 😅.

**Comment by Poopooracoocoo** [comment]
omg best laugh ever. got to ask my dad if these were bad words too just to make sure 🤣

**Comment by ShankarBUS** [comment]
@yukiokun057,

I'm really sorry if that was offensive.

Forgive me. I promise such thing wouldn't happen again.

**Pull request merged**
