### PR TITLE
a minor translation update for zh-CN and zh-Hans

### PR DESCRIPTION
**Pull request by imgradeone**
- Fixed an unnecessary translation
- Fixed a translation with a small issue (my mistake :( )

> Original: If you find any bugs, please open a new issue in the github repository.  
> Legacy translation: 如果发现任何 bug，请在 GitHub 仓库中**打**创建一个新 Issue。  
> New translation: 如果发现任何 bug，请在 GitHub 仓库中创建一个新 Issue。

### CODE REVIEW

**Comment by ShankarBUS** [comment]
@Samuel12321,

Isn't zh-Hans & zh-Hant enough?

Why are there zh-CN & zh-TW additionally?

**Comment by ShankarBUS** [comment]
@imgradeone,

What's the difference between zh-Hans, zh-Hant, zh-CN & zh-TW?

I'm confused 😅.

**Comment by imgradeone** [comment]
@ShankarBUS https://github.com/ShankarBUS/ModernFlyouts/issues/104#issuecomment-719890977

> Hello, the default simplified Chinese language of Windows is zh-CN, and in the latest version 0.7.8.0, the simplified Chinese and traditional Chinese added in the program are zh-Hans and zh-Hant respectively, which do not match zh-CN, so it may be the cause of the problem.

maybe that's why 😂

**Comment by ShankarBUS** [comment]
Oh ok 😄

**Comment by Samuel12321** [comment]
From what i understand zk-CN is a subset of zh-hans.
I added zh-CN due to reports that zh-hans wasn't automatically being set for people with display language set to zh-CN. I assumed this was because it wasn't the same language code even though they ware the same. To fix this i also added zh-CN.

**Comment by imgradeone** [comment]
so, merge, whrn? :(

**Comment by ShankarBUS** [comment]
Hey @Samuel12321,

Could you merge this ASAP?

**Pull request merged**
