### PR TITLE
merge

### PR DESCRIPTION
**Pull request by Samuel12321**

### CODE REVIEW

**Comment by ShankarBUS** [comment]
Hey pal, can you commit directly to this repo or squash merge PRs next time?

Don't get me wrong but the pull request are creating mutiple & unnecessary merge commits 😅 .

**Comment by Samuel12321** [comment]
of course, sorry ill squash merge PRs next time.

**Comment by ShankarBUS** [comment]
I'm asking out of curiosity, Can't you commit directly to this repo? Do collaborator have the access to commit directly?

**Comment by Samuel12321** [comment]
Yes i can, i just prefer to commit to my fork, and then merge. reduced chances of messing anything up

**Pull request merged**
