### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Poopooracoocoo**
Added info about keyboard backlight brightness and function (Fn) key (source: https://github.com/ShankarBUS/ModernFlyouts/issues/64#issuecomment-700873427 and #57)
Added opacity and timeout features to list
Minor grammar fixes
😊

### CODE REVIEW

**Review by Samuel12321 — COMMENTED** [review]
Looks Good. Thanks @Poopooracoocoo 
One suggestion, change  "This application is aimed at providing" to "This application aims to provide"

**Review by Samuel12321 — APPROVED** [review]

**Comment by Poopooracoocoo** [comment]
haha i thought about that 🤣

**Comment by ShankarBUS** [comment]
Ooooh a new contributor!

Welcome mate!

**Comment by ShankarBUS** [comment]
> https://github.com/ShankarBUS/ModernFlyouts/blob/5824d1eef6c68e63ab975308679948b782667b39/README.md#L95

Oof, I cringe looking at this silly mistake 🤦‍♂️.

`backing`? What the heck was I even on while typing that 😞.

**Pull request merged**
