### PR TITLE
Update French translations

### PR DESCRIPTION
**Pull request by Stealnoob**
Opening this PR to let you preview my changes on the new (potentially temporary) strings.
Feel free to let me know how to make exactly the changes, as I have seen it can be ambiguous on some comments.

Also making the PR a draft, as I made it as a Work In Progress following along the changes on the UI, and for discussion about localisation issues.

Note that I will squash / rebase the commits on my branch as I do the translations to avoid an history hell, so tell me if you want to merge it 😄

### CODE REVIEW

**Review by Samuel12321 — COMMENTED** [review]
Looks good, will wait till we have finalised the changes to the settings menu before merging.

**Comment by ShankarBUS** [comment]
Thanks again @Stealnoob!

Let's keep this PR open until I figure out what strings to add or remove.

I will finish the settings window update.

You can translate and push the changes I make to the strings onto this PR. Please make sure this PR's branch is up-to-date with the master branch.

@Samuel12321 will take care of this. Please squash merge 😁😅 this PR onto master once it is complete.

If you crash on any merge conflicts please let me know.

**Comment by ShankarBUS** [comment]
Thanks again @Stealnoob!

Let's keep this PR open until I figure out what strings to add or remove.

I will finish the settings window update.

You can translate and push the changes I make to the strings onto this PR. Please make sure this PR's branch is up-to-date with the master branch.

@Samuel12321 will take care of this. Please squash merge 😁😅 this PR onto master once it is complete.

If you crash on any merge conflicts please let me know.

**Comment by Samuel12321** [comment]
Sounds good

**Comment by ShankarBUS** [comment]
Hey @Samuel12321, should we add PR templates?

It will be helpful for contributors.

Did you figure out the contribution guidelines and how to set up their environment?

When are we gonna add the guidelines? Could you take care of it?

**Comment by Samuel12321** [comment]
> Did you figure out the contribution guidelines and how to set up their environment?

Haven't had time yet, but will soon.


I'll take care of the Contributing guidelines.

PR templates sound good

**Comment by Samuel12321** [comment]
@Stealnoob can you re-open this for the new branch

**Comment by Stealnoob** [comment]
Will do when I'm on my PC

**Comment by ShankarBUS** [comment]
Oops sorry, I deleted the master branch which automatically closed this PR.

Hey @Stealnoob, @Samuel12321 could both of you delete your fork or local clone and re-fork or re-clone.

@Stealnoob, you may need to re-do the work again on the new branch.

Sorry for the inconvenience 😅

**Comment by Stealnoob** [comment]
Yep, I've been following the history discussion and was expecting this, I will just restart fresh and paste the file on the new repo

**Pull request closed without merging**
