### PR TITLE
update Polish translation

### PR DESCRIPTION
**Pull request by sewerynkalemba**
Hi, 

I made some corrections to Polish translation.

Cheers! 🖐

### CODE REVIEW

**Comment by Samuel12321** [comment]
Thanks

**Comment by Samuel12321** [comment]
Will wait for some finalisation of the next release before merging.

**Comment by Samuel12321** [comment]
Hi @sewerynkalemba , 0.8.0.0 has been released, introducing significant changes. Can you update your translations for this release?

Thanks so much for your help.
This will be immediately merged once the translations are updated.

**Comment by sewerynkalemba** [comment]
@Samuel12321 updated :)

**Review by Samuel12321 — APPROVED** [review]

**Comment by Samuel12321** [comment]
Thanks so much for your help

**Comment by sewerynkalemba** [comment]
@Samuel12321 looks like https://github.com/ShankarBUS/ModernFlyouts/commit/8231e2b7146328c7bdd3b9c8c1518f766c99f696 overrode my changes. Let me know if you want me to rewrite them into new version of that file.

**Pull request merged**
