### PR TITLE
PL language

### PR DESCRIPTION
**Pull request by Daxxxis**
Polish language made by actual Pole

### CODE REVIEW

**Review by Samuel12321 — APPROVED** [review]
Hi, thanks so much for your help.
Will merge this for 0.8

**Comment by Daxxxis** [comment]
https://github.com/ShankarBUS/ModernFlyouts/pull/153#discussion_r515441260
Same for the next one

**Comment by Samuel12321** [comment]
Hi @Daxxxis, 0.8.0.0 has been released, introducing significant changes. Can you update your translations for this release?

Thanks so much for your help.
This will be immediately merged once the translations are updated.

**Comment by ShankarBUS** [comment]
@Daxxxis, sorry your inconvenience 😅

**Comment by Daxxxis** [comment]
> @Daxxxis, sorry your inconvenience 😅

I noticed that there is already a better Polish translation. (Another PR)

**Pull request closed without merging**
