### PR TITLE
Re-Updated Turkish Translation

### PR DESCRIPTION
**Pull request by ghost**
The words were not correct in the old translation. So I changed them.

### CODE REVIEW

**Comment by Samuel12321** [comment]
Thanks @ErenAKGUN2007 this will be visible in the next release.

**Comment by Samuel12321** [comment]
Hi @ErenAKGUN2007 ,
Sorry for the delay, just had a chance to review the translations, just wondering why some have been translated back into English?

**Comment by ErenAKGUN2007** [comment]
> Hi @ErenAKGUN2007 ,
> Sorry for the delay, just had a chance to review the translations, just wondering why some have been translated back into English?

Yes, but I don't have any idea

**Comment by Samuel12321** [comment]
> Yes, but I don't have any idea

sorry, i don't understand your reply?

**Comment by ErenAKGUN2007** [comment]
> > Yes, but I don't have any idea
> 
> sorry, i don't understand your reply?

I think I didn't understand correctly that you wrote it, but did you say that I translated some translations into English? If so, can you tell me which translation it is?

**Comment by Samuel12321** [comment]
`          <target state="needs-review-translation" state-qualifier="tm-suggestion">Araya Ekleme Modu</target>
          <target state="needs-review-translation" state-qualifier="tm-suggestion">Insert Modu</target>`

+ basically all the lock keys

**Comment by ErenAKGUN2007** [comment]
Even on windows these are written in English
image
image

**Pull request merged**
