### PR TITLE
Update zh-Hans (Chinese Simplified) translations

### PR DESCRIPTION
**Pull request by imgradeone**
because the MT contains soooo many issues

### CODE REVIEW

**Comment by ShankarBUS** [comment]
Thanks @imgradeone!

@Samuel12321 FYI.

Shouldn't the changes be made to the *.xlf file?

**Comment by Samuel12321** [comment]
@ShankarBUS, doesn't matter. Either work.

**Review by Samuel12321 — APPROVED** [review]
looks good, thanks for your help

**Comment by imgradeone** [comment]
It seems that the translation doesn't work.

Maybe, @Samuel12321 and @ShankarBUS , I will consider editing the *.xlf files and create another PR.

**Pull request merged**
