### PR TITLE
Corrects portuguese translations

### PR DESCRIPTION
**Pull request by lucasskluser**
First, what an amazing project!
Second, the Portuguese translations have been corrected.

### CODE REVIEW

**Comment by ShankarBUS** [comment]
Thanks @lucasskluser!

**Review by Samuel12321 — COMMENTED** [review]
Thanks so much for your help.
Unfortunately these changes need to be made to the .resx file for the language instead of the .xlf file as these are sometimes overwritten.

**Review by Samuel12321 — APPROVED** [review]

**Comment by Samuel12321** [comment]
thanks so much for your help

**Comment by lucasskluser** [comment]
@Samuel12321 should I copy these translations to `https://github.com/ShankarBUS/ModernFlyouts/blob/master/ModernFlyouts/Properties/Strings.pt.resx`?

**Comment by Samuel12321** [comment]
don't worry, i found out how to import them correctly.
the translations have been merged and should be visible in 0.8.0

**Pull request merged**
