### PR TITLE
Update 'ru' localization

### PR DESCRIPTION
**Pull request by yukiokun057**
Hello,

Made some updating for 'ru' localization

Best regards

### CODE REVIEW

**Comment by ShankarBUS** [comment]
Thank you for your contribution

**Comment by ShankarBUS** [comment]
Shall I megre this @yukiokun057

**Comment by yukiokun057** [comment]
Yeah, of course 🙂

**Comment by ShankarBUS** [comment]
Thanks again @yukiokun057

**Comment by Samuel12321** [comment]
Thanks so much for your help.
Unfortunately these changes need to be made to the .resx file for the language instead of the .xlf file as these are sometimes overwritten.

**Comment by ShankarBUS** [comment]
Should the **Multilingual App Toolkit** automatic convert the *.xlf files in the `MultilingualResources` a directory into *.resx files during build?

**Comment by Samuel12321** [comment]
no it only translates the .resx files into the selected languages then converts .resx to .xlf, not the other way round.

**Comment by Samuel12321** [comment]
> If so, the *.resx files will be the ones that changes during build. The *.xlf files should stay constant, shouldn't they?

other way round

**Comment by ShankarBUS** [comment]
Do you mean it converts `Strings.resx` file (the main file) into multiple languages and save them in the Properties directory with names such as `Strings.es.resx

Then why do we have the *.xlf files if they don't serve any purpose?

**Comment by ShankarBUS** [comment]
@Samuel12331

https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/use-mat#option-2-send-the-xlf-files-to-a-third-party-for-translation

**Comment by Samuel12321** [comment]
👍

**Pull request merged**
