### PR TITLE
Restore french translations

### PR DESCRIPTION
**Pull request by Stealnoob**
And it's back another time.

@Samuel12321, I think I understand why translations are being reverted.
When building on Visual Studio, it builds the .resx files from the .xlf, so I think changes must be done to the .xlf files

For what I did : I translated the strings properly on the .resx, then deleted and recreated the .xlf from the Multilingual App Toolkit extension (it automatically imports from the localized .resx file), and manually validated review-requested strings (when source and target are the same) on the standalone editor, and I finally have something clean

So if there are translations added and if you want to apply them from one file to another, make sure you don't build the solution (and at least the ModernFlyouts C# project) before you have done the changes 🙂

### CODE REVIEW

**Comment by Stealnoob** [comment]
Also sorting the new strings in the base strings.resx file for readability.

**Comment by Samuel12321** [comment]
Thanks so much @Stealnoob, will merge this for the next release

**Review by Samuel12321 — APPROVED** [review]

**Comment by Samuel12321** [comment]
Merged, Thanks so much @Stealnoob

**Comment by Samuel12321** [comment]
Will be visible in 0.8.2

**Comment by Stealnoob** [comment]
Wait, the merge commit broke both .resx files, and it doesn't even build (why do I have ocd of sorting things 🙃 ...)
Multilingual builds also fail even if I correct them, don't know why, but probably on my end.

**Comment by ShankarBUS** [comment]
@Samuel12321, what is going on?

This guy just did the PR two times and both of the times the translations are overwritten.

This is why we should have a contribution guidelines document.

Should contributors modify the *.xlf files or the *.resx files?

**Comment by Samuel12321** [comment]
@ShankarBUS there seems to be a problem preventing me and @Stealnoob building recently. This time the translations were applied correctly, i just reverted it to try to se if i could fix the problem. 
Are you experiencing XLF verification errors?

Will undo this revert once we fix the problem.

**Comment by Stealnoob** [comment]
@ShankarBUS
Actually the translations didn't get overwritten, the merge commit with upstream duplicated strings, which made the build fail.
Also MAT is somewhat confusing as at build time it changes the .xlf from the source strings.resx and also changes the localized .resx file from the .xlf...

@Samuel12321
Are the build errors the same error on the MSBuild Targets for MAT ? Because it doesn't tell what's wrong and it seems to come from nowhere.

**Comment by Samuel12321** [comment]
yup, they are ridiculously helpful.
They have me stumped too.

**Pull request merged**
