### PR TITLE
Spanish

### PR DESCRIPTION
**Pull request by peter9811**

### CODE REVIEW

**Comment by ShankarBUS** [comment]
Sorry, I can't add multiple language support for now 😅. We can do it after v1.0

Thanks anyways.

**Comment by peter9811** [comment]
I get it. Now that I read your answer in the Issues, I understand everything
And I added Spanish as a separate text document. If it is possible to add it, it might be ... if not, I can remove the pull

**Comment by ShankarBUS** [comment]
But please stay in contact, I'll find a way to add support for multiple languages within the next month.

**Comment by Samuel12321** [comment]
#17

**Pull request closed without merging**
