### PR TITLE
Update of french translations (for real this time)

### PR DESCRIPTION
**Pull request by Stealnoob**
I made the changes on the good file (.resx).
This is basically the translations from #121 , as they were made on the .xlf file (if you didn't see it).

### CODE REVIEW

**Comment by Stealnoob** [comment]
Didn't see the new enums strings, so I have just added them.

**Comment by ShankarBUS** [comment]
@Samuel12321 FYI.

Could you please take care of this translation PRs? I need to focus on v0,8 work,

**Comment by ShankarBUS** [comment]
Thanks again @Stealnoob!

**Review by Samuel12321 — APPROVED** [review]
Looks great, thanks so much for your help.

**Pull request merged**
