### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Cyberdroid1**
- Rename "Modernflyouts flyout" to Flyout
- Airplane mode default flyout

### CODE REVIEW

**Comment by ShankarBUS** [comment]
I guess it is fine how it ready is.

ModernFlyouts is the name of the app.

So technically **"ModernFlyouts Flyout"** is correct. (analogous to Windows default flyout)

Thanks for your contribution though.

@Samuel12321, any thoughts?

Keep this open. After a short discussion, we can make some more changes and merge this afterwards.

**Comment by Cyberdroid1** [comment]
We must accept the word ModernFlyout as a "replacement" for the word "flyout". It sounds better too 😁

**Comment by ShankarBUS** [comment]
Then add some space between Modern and flyout

**Comment by Samuel12321** [comment]
I personally think it should change to just "ModernFlyouts" remove the flyout.

**Comment by Cyberdroid1** [comment]
> I personally think it should change to just "ModernFlyouts" remove the flyout.

Why plural?



> Then add some space between Modern and flyout

Would you like to add space between the app name? No, right? Its good like this.

**Comment by ShankarBUS** [comment]
@Samuel12321,

Yup, I agree!

**Comment by ShankarBUS** [comment]
@Cyberdroid1,

> Why plural?

It's the name of our app. It's plural!

> Would you like to add space between the app name? No, right? Its good like this.

No, it's not good to rename our app to ModernFlyout. I suggested a change like this `modern flyout` vs `old flyout`

**Comment by Cyberdroid1** [comment]
> No, it's not good to rename our app to ModernFlyout. I suggested a change like this `modern flyout` vs `old flyout`

Bruh wait. I am not suggesting you to rename the app. I am just telling that we must take the word "ModernFlyouts" as a noun, which can have singular and plural. We are re-defining english, people!

**Comment by ShankarBUS** [comment]
> Bruh wait. I am not suggesting you to rename the app. I am just telling that we must take the word "ModernFlyouts" as a noun, which can have singular and plural. We are re-defining english, people!

Not renaming the apps... oops, I mean it wrong. I tried to mean not use new term which looks similar to the app's name
@Samuel12321 & I want it to be just **"ModernFlyouts"**, not **"ModernFlyout"**

**Comment by Cyberdroid1** [comment]
I am not able to understand the reasoning behind this, 😅. Can you explain the reason?

**Comment by ShankarBUS** [comment]
> I am not able to understand the reasoning behind this, 😅. Can you explain the reason?

It must be either ""ModernFlyouts" or  ""modern flyout" not "ModernFlyout"

**Comment by Cyberdroid1** [comment]
I am asking for the reason behind this...

**Comment by Samuel12321** [comment]
First of all, this app generates the most intense language orientated discussions i have seen in a while. 😉 I'll take that to mean a lot of people care deeply about the app.
My reasoning behind "ModernFlyouts" instead of "ModernFlyout" is that as this is not Windows's official new 'ModernFlyout' as 'ModernFlyout' Suggests.
Furthermore "ModernFlyouts" suggests that it is "ModernFlyouts 's" flyout. (Sorry for the incorrect England)

**Comment by Cyberdroid1** [comment]
> My reasoning behind "ModernFlyouts" instead of "ModernFlyout" is that as this is not Windows's official new 'ModernFlyout' as 'ModernFlyout' Suggests.

We must strive to do that, that should be the motive of the app, no? 😜😜😁

**Comment by Samuel12321** [comment]
Tell you what, if it is ever officially integrated into windows, we can change it to "ModernFlyout" from "ModernFlyouts"😉

**Comment by Cyberdroid1** [comment]
Let us imagine that it happened already 🤣🤣

(But the sad truth is that it might never happen....)

**Comment by ShankarBUS** [comment]
> Tell you what, if it is ever officially integrated into windows, we can change it to "ModernFlyout" from "ModernFlyouts"😉

What does the name has to do anything with being official or unofficial.

I named it this way because it contains a set of flyouts which can invidually replace the Windows provided ones.

>we can change it to "ModernFlyout" from "ModernFlyouts"😉

You think MS would allow us to do that after they integrate it? They'll rebrand it on their own. Remember Wox? (now called PowerLauncher in PowerToys). It'll be up-to them, they'll what features to add/remove what bug to fix/not.
Never get into the hands of corporate, you'll lose the freedom.

> (But the sad truth is that it might never happen....)

Yep! I won't happen because this app is useless TBH. They'll never even consider this

**Comment by Samuel12321** [comment]
It was just a joke.😉🤣

> Yep! I won't happen because this app is useless TBH. They'll never even consider this

wow that's positive. A lot of people think its a great app.

**Comment by Samuel12321** [comment]
> I named it this way because it contains a set of flyouts which can invidually replace the Windows provided ones.

I was referring to the text in the readme, not the name of the app.

**Comment by ShankarBUS** [comment]
Oh, I must have misread it

**Comment by ShankarBUS** [comment]
@Samuel12321,

> wow that's positive. A lot of people think its a great app.

I'm serious! Just look at our code base! And compare it to other apps such as EarTrumpet, Lively, Files & etc.

I piss my pants just by looking at their repo!

I feel like our app got more attention than it deserves. Our code base looks utterly bad. No consistency, No pattern. Just spaghett!

I got anxious when you said we have about ~12k users. Bruh! I was at the verge of discontinuing this project because of the problems in it (no topmost support, the Win 10 2004+ bug, the settings bug) and our weak code base.

Even 1000 users is high for this app at this stage!

I don't know what we are going to do with this in the future 🤪.

Without you, I'll be left alone to maintaining this repo, tracking issues, planning projects and publishing the app by myself.

This app would be nothing without you! I gotta admit it.

We neither have a professional readme nor images.

I want to improve this but...

As long as you stick together, I'll do my best

**Comment by Cyberdroid1** [comment]
So, modernflyout or modernflyouts for the screenshots in the readme ?

**Comment by Samuel12321** [comment]
modernflyouts

**Comment by Cyberdroid1** [comment]
@ShankarBUS Bruh, talk about the present, not the distant future. That will keep you motivated 😉

**Comment by Samuel12321** [comment]
@ShankarBUS, i think we all underestimated how much people hate the windows default flyouts.
FYI: we are now just under 15k active users (14,872).
**Don't forget ear trumpet and files have been around for a while** (Files since mid 2018 and ear trumpet since mid 2015). 
A lot of these things such as professional readme, images and perfectly consistent code take quite a lot of time to get sorted, often they don't happen till the project is very well established.

Another thing that takes time to develop is community contributions and support. We are just starting to get this but it will help speed up and improve development, as well as bring new and innovative ideas to the project.

Regarding problems - while there has been a perceived increase due to the significant number of new users, my current reports from MS Store show that the app is getting significantly more reliable.
Our app also has the disadvantage of being built for an OS which doesn't have the best history in terms of bug free behaviour, eg the 2004 bug you mentioned.

> I don't know what we are going to do with this in the future 🤪.

The community has already come up with many great suggestions, and i have no doubt that they will continue to do so.

> Without you, I'll be left alone to maintaining this repo, tracking issues, planning projects and publishing the app by myself. This app would be nothing without you! I gotta admit it.

Thanks. But don't forget you have done most of the heavy lifting, I have mostly taken on an oversight role with this project. When i get more time, i hope to be able to contribute more to the code base. With that being said i am happy with what i am doing now.

> As long as you stick together, I'll do my best

I plan on sticking with this project as long as its around.

Well-done on all the brilliant work so far my friend.
I will try to put together a bit more of a development roadmap which may help seeing where to go next.

image

**Review by Samuel12321 — APPROVED** [review]
Looks good, thanks @Cyberdroid1

**Comment by Cyberdroid1** [comment]
@Samuel12321 Do check out the changes too I just made.

**Comment by Cyberdroid1** [comment]
Now that is a big motivating sppech, TBH.  👌

**Comment by ShankarBUS** [comment]
@Samuel12321,



Thanks bro ❤️

**Comment by ShankarBUS** [comment]
> When i get more time, i hope to be able to contribute more to the code base.

You know coding? Buu... Why didn't you tell me?

I thought you didn't know programming!

¡oʇuǝɯoɯ ɥnɹᙠ (NZ upside down joke go brrrr)

**Comment by Samuel12321** [comment]
I do know programming, just mostly python and a special variant of C.

This is my first time working with C#, so still learning.

**Comment by Cyberdroid1** [comment]
So you 2 know coding, noice. Me just a noob here 😂

**Pull request merged**
