### PR TITLE
0.8.0 French translations

### PR DESCRIPTION
**Pull request by Stealnoob**
Here are the new French translations.
I tried to make the localized file match the layout of the original strings.resx file.

I also think some of my older changes have been overwritten with machine translation from the XLIFF files. I don't know how you port the changes from one file to another, and which one of the files, the .xlf or the .resx is actually important for the app (some documentation about that could be nice, with #122 probably).

Otherwise, nice to see this app grow and get this many options, and looking forward for more translations to do 😄.

PS : I don't know if I got in the beta flights, as I filled the form, but didn't receive any confirmation, nor seeing a change in the Microsoft Store, so i don't know if it works as intended...

### CODE REVIEW

**Comment by Samuel12321** [comment]
> I also think some of my older changes have been overwritten with machine translation from the XLIFF files. I don't know how you port the changes from one file to another, and which one of the files, the .xlf or the .resx is actually important for the app (some documentation about that could be nice, with #122 probably).

Agreed, will work on this

>Otherwise, nice to see this app grow and get this many options, and looking forward for more translations to do 😄.

Thanks so much for your help @Stealnoob.

PS : I don't know if I got in the beta flights, as I filled the form, but didn't receive any confirmation, nor seeing a change in the Microsoft Store, so i don't know if it works as intended...

Please let me know when you get 0.8.0 so i can check if it worked properly. So far 0.8.0 is only in beta ring.
Unfortunately there is no confirmation. Store doesn't make any of this easy.
There may be a delay in getting enrolled as i have to manually add people to the beta ring. However i do check and make sure everyone is added before a new release.

**Comment by Stealnoob** [comment]
Please wait a bit before merging, I created the pull request right after you commited, so it makes unwanted merge commits, and I will try to rebase

**Review by Samuel12321 — APPROVED** [review]
Looks great thanks

**Comment by Stealnoob** [comment]
Done, so you can fast-forward now.

> Please let me know when you get 0.8.0 so i can check if it worked properly.
Ok, I will check when it's released (plus the certification process time)

**Comment by Stealnoob** [comment]
@Samuel12321 Good news, it did update just now with the 0.8.0.0 version and it seems to work normally.
Clearly a shame it shows as a classic update on Microsoft Store and that there is no indication anywhere of either it's a public or a beta build...

**Pull request merged**
